name: Lint
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Python Setup
      uses: ./.github/actions/python-setup-action
      with:
        python-version: '3.12'

    - name: Check code formatting with Black
      run: black --check . --target-version=py312

    - name: Check types with mypy
      run: mypy .
