name: Lint
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

    - name: Python Setup
      uses: ./.github/actions/python-setup-action
      with:
        python-version: '3.12'

    - name: Check code formatting with Black
      run: black --check .

    - name: Check types with mypy
      run: mypy .
