name: Lint

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Python Setup
      uses: ./.github/actions/python-setup-action
      with:
        python-version: '3.12'

    - name: Check code formatting with Black
      run: black --check .

    - name: Check types with mypy
      run: mypy .
