name: CI, Build, Test, Lint, and Release
permissions:
  contents: read

on:
  push:
    tags:
      - "v*"

jobs:
  test:
    uses: ./.github/workflows/test.yml

  lint:
    uses: ./.github/workflows/lint.yml
    needs: test

  build:
    uses: ./.github/workflows/wheel.yml
    needs: lint

  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
      attestations: write
    needs: build
    steps:
    - name: Checkout repository
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Python Setup and Install Dependencies
      uses: ./.github/actions/python-setup-action
      with:
        python-version: "3.12"

    - name: Build the package
      run: python -m build

    - name: Create GitHub Release
      uses: ncipollo/release-action@339a81892b84b4eeb0f6e744e4574d79d0d9b8dd # v1.21.0
      with:
        artifacts: "dist/*"
        generateReleaseNotes: true

    - name: Generate attestation
      uses: actions/attest-build-provenance@a2bbfa25375fe432b6a289bc6b6cd05ecd0c4c32 # v4.1.0
      with:
        subject-path: "dist/*"
