name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    uses: ./.github/workflows/python-setup.yml

    steps:
    - name: Run pytest
      uses: quantco/pytest-action@v2
      with:
        verbose: true
        emoji: true
        job-summary: true
        custom-arguments: '-q'
        click-to-expand: true
        report-title: 'Test Report'
