name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Python Setup
      uses: ./.github/actions/python-setup-action
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run pytest
      uses: quantco/pytest-action@v2
      with:
        verbose: true
        emoji: true
        job-summary: true
        custom-arguments: '-q'
        click-to-expand: true
        report-title: 'Test Report'
