name: Python Tests

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
        cache: pip
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run pytest
      uses: quantco/pytest-action@v3
      with:
        verbose: true
        emoji: true
        job-summary: true
        custom-arguments: '-q'
        click-to-expand: true
        report-title: 'Test Report'