name: Python Tests
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Python Setup
      uses: ./.github/actions/python-setup-action
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run pytest
      run: python -m pytest --junit-xml=${{ runner.temp }}/test-results.xml

    - name: Parse pytest results
      if: always()
      uses: pmeier/pytest-results-action@fdc7f18d9934e38aca411ca9557e6577bd25ca9c # v0.9.0
      with:
        path: ${{ runner.temp }}/test-results.xml
        summary: true
        display-options: fEX
        fail-on-empty: true
        title: Pytest results
