name: Python Tests
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12", "3.13", "3.14"]
    steps:
    - name: Checkout code
      uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3

    - name: Python Setup
      uses: ./.github/actions/python-setup-action
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run pytest
      run: python -m pytest --junit-xml=${{ runner.temp }}/test-results.xml

    - name: Parse pytest results
      if: always()
      uses: pmeier/pytest-results-action@0841ca7226ab155943837380769373a5dd14d7ed # v0.8.0
      with:
        path: ${{ runner.temp }}/test-results.xml
        summary: true
        display-options: fEX
        fail-on-empty: true
        title: Pytest results
