name: Build Wheel
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.12"]
    steps:

    - name: Checkout code
      uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

    - name: Python Setup
      uses: ./.github/actions/python-setup-action
      with:
        python-version: ${{ matrix.python-version }}

    - name: Build the package
      run: python -m build

    - name: Check wheel
      run: twine check dist/*

    - name: Upload Wheel as artifact
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: wheel-package
        path: dist/*
